version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: doodle_postgres
    environment:
      POSTGRES_DB: doodlejump
      POSTGRES_USER: doodleuser
      POSTGRES_PASSWORD: doodlepass184848
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - doodle_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    container_name: doodle_backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=doodlejump
      - DB_USER=doodleuser
      - DB_PASSWORD=doodlepass184848s
      - SECRET_KEY=${SECRET_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_SECRET_TOKEN=${WEBHOOK_SECRET_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - doodle_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    container_name: doodle_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - doodle_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: doodle_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - doodle_network
    restart: unless-stopped

  # Certbot для автоматического получения SSL
  certbot:
    image: certbot/certbot
    container_name: doodle_certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email podruzhka@mail.ru --agree-tos --no-eff-email -d podruzhka.store
    depends_on:
      - nginx

volumes:
  postgres_data:

networks:
  doodle_network:
    driver: bridge